<?php

namespace Model;

class Chanson extends Album
{
    private $id;
    private $chanson;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }
    public function setId($id)
    {
        parent::setId($id); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function getChanson()
    {
        return $this->chanson;
    }

    /**
     * @param mixed $chanson
     */
    public function setChanson($chanson)
    {
        $this->chanson = $chanson;
    }

    public function addChanson()
    {
        //ajout chanson
    }

    public function deleteChanson()
    {
        //supprimer chansons
    }

    public function updateChanson()
    {
        //MAJ chanson
    }


}