<?php
/**
 * Created by PhpStorm.
 * User: sylvain
 * Date: 07/03/18
 * Time: 18:20
 */

namespace Model;


class GoodiesManager extends EntityManager
{
    const TABLE = 'Goodies';


    public function __construct()
    {
        parent::__construct(self::TABLE);
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    public function GoodiesParCategorie($GetId)
    {
        $statement = $this->conn->prepare("SELECT * FROM $this->table WHERE categorie_id =$GetId");
        $statement->execute();
        return $statement->fetchAll(\PDO::FETCH_ASSOC);
    }


}